server:
    port: 8081
    context-path: /auth
spring:
    application:
        name: OAuth-server
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/
security:
    basic:
      enabled: false