server:
    port: 8082
    context-path: /ui
spring:
    application:
        name: OAuth-client
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:1111/eureka/